SET FOREIGN_KEY_CHECKS=0;
DELETE FROM district_adjacency;
DELETE FROM game_zones;
SET FOREIGN_KEY_CHECKS=1;
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (1, 'Game Box', NULL);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (2, 'Chairs', NULL);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (3, 'Table', NULL);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (4, 'P1-P5 Areas', 3);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (5, 'ARBITER Area', 3);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (6, 'Central Area', 3);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (7, 'Supply', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (8, 'Accord Placement Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (9, 'Session Timeline Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (10, 'Initiative Strip Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (11, 'Chorus Activity Track Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (12, 'Situation Report Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (13, 'Public Standing Track Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (14, 'City', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (15, 'Ring 0', 14);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (16, 'Ring 1', 14);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (17, 'Ring 2', 14);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (18, 'Ring 3', 14);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (19, 'Ring 1 Modifier Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (20, 'Ring 2 Modifier Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id) VALUES (21, 'Ring 3 Modifier Area', 6);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (600, 'Chorus Node', 15, 0, 1);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (601, 'Military Installation', 16, 0, 2);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (602, 'Government Citadel', 16, 1, 5);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (603, 'Chorus Research', 16, 2, 1);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (604, 'Financial Sanctum', 16, 3, 3);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (605, 'Regulatory District', 17, 0, 5);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (606, 'Power Grid', 17, 1, 4);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (607, 'Logistics Center', 17, 2, 4);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (608, 'Research Institute', 17, 3, 1);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (609, 'Data Exchange', 17, 4, 1);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (610, 'Communications Hub', 17, 5, 2);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (611, 'Financial Clearinghouse', 17, 6, 3);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (612, 'Industrial Fringe', 18, 0, 4);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (613, 'Transit Hub', 18, 1, 4);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (614, 'Civic Center', 18, 2, 5);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (615, 'Residential Quarter', 18, 3, 5);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (616, 'University Perimeter', 18, 4, 1);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (617, 'Media District', 18, 5, 2);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (618, 'Broadcast Tower', 18, 6, 2);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (619, 'Observation Post', 18, 7, 2);
INSERT INTO game_zones (id, zone_name, parent_zone_id, position, resource_type_id) VALUES (620, 'Commercial Strip', 18, 8, 3);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (600, 601, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (600, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (600, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (600, 604, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (601, 600, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (601, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (601, 605, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (601, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 600, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 601, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 607, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (602, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 600, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 604, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 609, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (603, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (604, 600, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (604, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (604, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (604, 611, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (605, 601, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (605, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (605, 612, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (605, 613, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 601, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 605, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 607, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 613, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (606, 614, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (607, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (607, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (607, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (607, 614, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (607, 615, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 602, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 607, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 609, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 615, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 616, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (608, 617, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (609, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (609, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (609, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (609, 617, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (609, 618, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 603, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 604, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 609, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 611, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 618, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (610, 619, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (611, 604, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (611, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (611, 619, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (611, 620, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (612, 605, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (612, 613, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (613, 605, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (613, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (613, 612, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (613, 614, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (614, 606, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (614, 607, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (614, 613, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (614, 615, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (615, 607, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (615, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (615, 614, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (615, 616, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (616, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (616, 615, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (616, 617, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (617, 608, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (617, 609, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (617, 616, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (617, 618, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (618, 609, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (618, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (618, 617, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (618, 619, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (619, 610, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (619, 611, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (619, 618, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (619, 620, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (620, 611, 1, 1);
INSERT IGNORE INTO district_adjacency (district_id, adjacent_district_id, allow_ingress, allow_egress) VALUES (620, 619, 1, 1);
