DROP TABLE IF EXISTS district_adjacency;

CREATE TABLE district_adjacency (
    origin_ring TINYINT NOT NULL,
    origin_position TINYINT NOT NULL,
    origin_district_name VARCHAR(255) NOT NULL,
    adjacent_ring TINYINT NOT NULL,
    adjacent_position TINYINT NOT NULL,
    adjacent_district_name VARCHAR(255) NOT NULL,
    allow_ingress BOOLEAN DEFAULT TRUE,
    allow_egress BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (origin_ring, origin_position, adjacent_ring, adjacent_position)
);

INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (0, 0, "Chorus Node", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (0, 0, "Chorus Node", 1, 0, "Military Installation", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (0, 0, "Chorus Node", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (0, 0, "Chorus Node", 1, 3, "Financial Sanctum", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 0, "Military Installation", 0, 0, "Chorus Node", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 0, "Military Installation", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 0, "Military Installation", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 0, "Military Installation", 2, 0, "Regulatory District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 0, 0, "Chorus Node", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 1, 0, "Military Installation", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 2, 2, "Logistics Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 1, "Government Citadel", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 0, 0, "Chorus Node", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 1, 3, "Financial Sanctum", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 2, 4, "Data Exchange", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 2, "Chorus Research", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 3, "Financial Sanctum", 0, 0, "Chorus Node", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 3, "Financial Sanctum", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 3, "Financial Sanctum", 2, 6, "Financial Clearinghouse", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (1, 3, "Financial Sanctum", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 0, "Regulatory District", 1, 0, "Military Installation", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 0, "Regulatory District", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 0, "Regulatory District", 3, 0, "Industrial Fringe", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 0, "Regulatory District", 3, 1, "Transit Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 1, 0, "Military Installation", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 2, 2, "Logistics Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 2, 0, "Regulatory District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 3, 1, "Transit Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 1, "Power Grid", 3, 2, "Civic Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 2, "Logistics Center", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 2, "Logistics Center", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 2, "Logistics Center", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 2, "Logistics Center", 3, 3, "Residential Quarter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 2, "Logistics Center", 3, 2, "Civic Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 1, 1, "Government Citadel", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 2, 4, "Data Exchange", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 2, 2, "Logistics Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 3, 4, "University Perimeter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 3, 5, "Media District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 3, "Research Institute", 3, 3, "Residential Quarter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 4, "Data Exchange", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 4, "Data Exchange", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 4, "Data Exchange", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 4, "Data Exchange", 3, 5, "Media District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 4, "Data Exchange", 3, 6, "Broadcast Tower", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 1, 2, "Chorus Research", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 1, 3, "Financial Sanctum", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 2, 6, "Financial Clearinghouse", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 2, 4, "Data Exchange", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 3, 6, "Broadcast Tower", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 5, "Communications Hub", 3, 7, "Observation Post", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 6, "Financial Clearinghouse", 1, 3, "Financial Sanctum", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 6, "Financial Clearinghouse", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 6, "Financial Clearinghouse", 3, 8, "Commercial Strip", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (2, 6, "Financial Clearinghouse", 3, 7, "Observation Post", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 0, "Industrial Fringe", 2, 0, "Regulatory District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 0, "Industrial Fringe", 3, 1, "Transit Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 1, "Transit Hub", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 1, "Transit Hub", 2, 0, "Regulatory District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 1, "Transit Hub", 3, 0, "Industrial Fringe", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 1, "Transit Hub", 3, 2, "Civic Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 2, "Civic Center", 2, 1, "Power Grid", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 2, "Civic Center", 2, 2, "Logistics Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 2, "Civic Center", 3, 3, "Residential Quarter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 2, "Civic Center", 3, 1, "Transit Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 3, "Residential Quarter", 2, 2, "Logistics Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 3, "Residential Quarter", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 3, "Residential Quarter", 3, 4, "University Perimeter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 3, "Residential Quarter", 3, 2, "Civic Center", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 4, "University Perimeter", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 4, "University Perimeter", 3, 5, "Media District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 4, "University Perimeter", 3, 3, "Residential Quarter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 5, "Media District", 2, 4, "Data Exchange", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 5, "Media District", 2, 3, "Research Institute", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 5, "Media District", 3, 4, "University Perimeter", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 5, "Media District", 3, 6, "Broadcast Tower", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 6, "Broadcast Tower", 2, 4, "Data Exchange", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 6, "Broadcast Tower", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 6, "Broadcast Tower", 3, 5, "Media District", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 6, "Broadcast Tower", 3, 7, "Observation Post", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 7, "Observation Post", 2, 6, "Financial Clearinghouse", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 7, "Observation Post", 2, 5, "Communications Hub", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 7, "Observation Post", 3, 8, "Commercial Strip", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 7, "Observation Post", 3, 6, "Broadcast Tower", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 8, "Commercial Strip", 2, 6, "Financial Clearinghouse", 1, 1);
INSERT INTO district_adjacency (origin_ring, origin_position, origin_district_name, adjacent_ring, adjacent_position, adjacent_district_name, allow_ingress, allow_egress) VALUES (3, 8, "Commercial Strip", 3, 7, "Observation Post", 1, 1);
